### ISSUE TITLE
(Custom Modes) Toggled MIDI notes do not indicate status

### ISSUE THREAD

**Issue by tsmorrill** [mat1jaczyyy/lpp-performance-cfw#50] opened 2021-03-14 12:12 UTC
MIDI notes that are set to toggle do not light up when pressed.

**Comment by mat1jaczyyy** [comment] 2021-03-14 19:37
This worked on my build, can you please send a custom mode that contains faulty behavior?

**Comment by rasch3n** [comment] 2021-03-15 07:25
I have some same kind of issue but just if I have 2 custom pages witch toggles. One is working and the other one not.

**Comment by tsmorrill** [comment] 2021-03-15 10:58
Here is my custom mode. https://www.dropbox.com/s/y2qgxjjio2c7xwd/Harmonic%20Hold.syx?dl=0 I had this in the second custom mode slot.

**Comment by rasch3n** [comment] 2021-03-15 11:02
in my setup also just the first page was working!

**Comment by mat1jaczyyy** [comment] 2021-03-15 13:46
Thanks. My Launchpad Pro is out of commission at the moment, I'll check as soon as I'm back to a working state.

**Comment by rpgaleksy** [comment] 2021-03-17 14:40
This is intended behavior.
If velocity sensitivity is enabled you need to press a button at 127 (maximum) velocity for the toggles to switch state.
Disabling velocity sensitivity results in the behavior you expect.
This is exactly how the Launchpad X does it as well.

**Comment by tsmorrill** [comment] 2021-03-20 22:02
Clarification, is it intended behavior to have a mismatch between visual state and MIDI state? As is, I can have a note held at 96 velocity, but the interface will not reflect that the note is active.

**Comment by rpgaleksy** [comment] 2021-03-20 22:27
Is that so? I'll check that out and compare CFW to X firmware shortly,
As far as I know, mat1 recreated the Xs behavior 1-to-1 in CFW custom modes.

**Comment by mat1jaczyyy** [comment] 2021-03-22 12:53
> 
> 
> Clarification, is it intended behavior to have a mismatch between visual state and MIDI state? As is, I can have a note held at 96 velocity, but the interface will not reflect that the note is active.

@tsmorrill This issue exists on the Launchpad X and Mini MK3 when using custom modes "the official way" in a velocity sensitive environment. Whether Novation intended this behavior in their official implementation is up for debate.

When talking about CFW though, it is considered intended behavior because our goal is to implement the custom modes as accurately as possible to the Launchpad X, making sure there are as little differences as possible.

**Comment by mat1jaczyyy** [comment] 2021-04-04 10:43
While I understand it's confusing, I'm closing as this is intended behavior

**Closed by mat1jaczyyy** 2021-04-04 10:43 UTC
Labels: bug
